spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:~/test3
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
url: http://localhost:2221/items/{itemName}
    